### PR TITLE
Example tcpinfo sidecar (and Go 1.12 -> 1.18)

### PR DESCRIPTION
**Pull request by stephen-soltesz**
This change adds a simple reference implementation of a sidecar service that listens on the tcp-info eventsocket interface.

This change also updates the Go version from 1.12 to 1.18 and adds go.mod/go.sum files.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/tcp-info/130)

### CODE REVIEW

**Comment by SaiedKazemi** [comment]
@stephen-soltesz I will look at this PR today.

**Comment by SaiedKazemi** [comment]
*[`Dockerfile.example` line 10 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uFejy0kXgi6Gr9vrn:-N3uFejy0kXgi6Gr9vro:babg46t) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/Dockerfile.example#L10)):*
> ```
> 
> # Put it in its own image.
> FROM alpine
> ```

Does it make sense to specify a version like `alpine:3.16` as it's done in `Dockerfile`?

**Comment by SaiedKazemi** [comment]
*[`cmd/example-eventsocket-client/main.go` line 60 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uGbsoE3KLxjVqD_Wn:-N3uGbsoE3KLxjVqD_Wo:bh5qxb0) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L60)):*
> ```Go
> func main() {
> 	flag.Parse()
> 	rtx.Must(flagx.ArgsFromEnv(flag.CommandLine), "Could not get args from environment variables")
> ```

Error strings should not be capitalized (unless beginning with an exported name, a proper noun or an acronym) and should not end with punctuation.
go/go-style/decisions#error-strings

**Comment by SaiedKazemi** [comment]
*[`cmd/example-eventsocket-client/main.go` line 64 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uGku30vUdc-tE52xP:-N3uGku30vUdc-tE52xQ:b-5asro2) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L64)):*
> ```Go
> 
> 	if *eventsocket.Filename == "" {
> 		panic("-tcpinfo.eventsocket path is required")
> ```

Can we use log.Fatal() here?

Do not use panic for normal error handling.
go/go-style/decisions#dont-panic

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/tcp-info/130)* status: 0 of 1 LGTMs obtained

___
*[`Dockerfile.example` line 10 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uFejy0kXgi6Gr9vrn:-N3uJiPL9J5PuPhQrxvv:blr1hjl) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/Dockerfile.example#L10)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Does it make sense to specify a version like `alpine:3.16` as it's done in `Dockerfile`?
</blockquote></details>

Absolutely. Done.
___
*[`README.md` line 44 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uG23kEuN5ur3pKfdb:-N3uKixy20VFME8Ity_r:b-fflhqt) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/README.md#L44)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

How about also telling the users how they can test by providing an example command like the following?

`docker exec -it tcp-info_tcpinfo_1 wget www.google.com`
</blockquote></details>

Great idea. Done.
___
*[`cmd/example-eventsocket-client/main.go` line 49 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uGLpA87EyZF89Z-l4:-N3uMt3R5rj3Re7ddeif:bjbqjo9) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L49)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Strictly speaking, we don't need this function and the example code can be further simplified.
</blockquote></details>

I agree in principle - and I debated just keeping the Open/Close methods. But, a key point I wanted to illustrate with this example is that the current tcp-info interface is blocking, and a client should separate the activity of reading events and processing the events, lest events are missed or a backlog form. What would be a better way to do this?
___
*[`cmd/example-eventsocket-client/main.go` line 60 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uGbsoE3KLxjVqD_Wn:-N3uL_4k19LfkE9cSlbY:b-837i3v) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L60)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Error strings should not be capitalized (unless beginning with an exported name, a proper noun or an acronym) and should not end with punctuation.
go/go-style/decisions#error-strings

</blockquote></details>

Okay.
___
*[`cmd/example-eventsocket-client/main.go` line 61 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uH-Ia5nwlpuX366Yj:-N3uMdIXCUb43FvhHdP9:bavy64q) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L61)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Does it make sense to move this before `rtx.Must()` or even make it the very first line of `main()`?
</blockquote></details>

Moved to top of main.
___
*[`cmd/example-eventsocket-client/main.go` line 64 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uGku30vUdc-tE52xP:-N3uLQDW8ETT49hFD8Zf:b-896fix) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L64)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Can we use log.Fatal() here?

Do not use panic for normal error handling.
go/go-style/decisions#dont-panic
</blockquote></details>

Done.

**Comment by SaiedKazemi** [comment]
*[`cmd/example-eventsocket-client/main.go` line 49 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uGLpA87EyZF89Z-l4:-N3uPKWcA9gzb-vzr0O2:bb9c5gm) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

I agree in principle - and I debated just keeping the Open/Close methods. But, a key point I wanted to illustrate with this example is that the current tcp-info interface is blocking, and a client should separate the activity of reading events and processing the events, lest events are missed or a backlog form. What would be a better way to do this?
</blockquote></details>

Oh, I understand the motivation now.  You wanted the fastest possible open and close handlers.  I think if you explain this in a comment it will be clear that the minimum we need is a couple of handlers but we're adding a goroutine to offload processing from the handlers in order to avoid any complications arising from slow handlers.

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/tcp-info/130)* status: 0 of 1 LGTMs obtained

___
*[`cmd/example-eventsocket-client/main.go` line 49 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uGLpA87EyZF89Z-l4:-N3uVJ4i02bM2rBUeEVf:b-833305) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L49)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Oh, I understand the motivation now.  You wanted the fastest possible open and close handlers.  I think if you explain this in a comment it will be clear that the minimum we need is a couple of handlers but we're adding a goroutine to offload processing from the handlers in order to avoid any complications arising from slow handlers.
</blockquote></details>

PTAL?

**Comment by SaiedKazemi** [comment]
*[`cmd/example-eventsocket-client/main.go` line 70 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uWj6cBy3LMSG9Epar:-N3uWj6cBy3LMSG9Epas:b3gnkdl) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L70)):*
> ```Go
> 
> 	// Process events received by the eventsocket handler. The goroutine will
> 	// block until an open even occurs.
> ```

s/even/event/

**Comment by SaiedKazemi** [comment]
*[`cmd/example-eventsocket-client/main.go` line 49 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uGLpA87EyZF89Z-l4:-N3uWpjiDh226Yo4CNpm:b-vs1pr4) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L49)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

PTAL?
</blockquote></details>

Looks good.

**Review by SaiedKazemi — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/m-lab/tcp-info/130)* status: 0 of 1 LGTMs obtained

**Comment by SaiedKazemi** [comment]
A minor typo correction, otherwise :lgtm:

**Comment by SaiedKazemi** [comment]
*[`Dockerfile.example` line 1 at r3](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uYQ-l81sJXiSns_J-:-N3uYQ-l81sJXiSns_J0:bfuhfs1) ([raw file](https://github.com/m-lab/tcp-info/blob/7e2dfbd4731336d05eef848626b9bc33239d1647/Dockerfile.example#L1)):*
> ```
> # Build uuid-annotator
> ```

Should this be example-eventscoket-client instead of uuid-annotator?

**Review by stephen-soltesz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/m-lab/tcp-info/130)* status: :shipit: complete! 1 of 1 LGTMs obtained

___
*[`Dockerfile.example` line 1 at r3](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uYQ-l81sJXiSns_J-:-N3uYhZoEzZ7LANzdQ_s:bqq9vr) ([raw file](https://github.com/m-lab/tcp-info/blob/7e2dfbd4731336d05eef848626b9bc33239d1647/Dockerfile.example#L1)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Should this be example-eventscoket-client instead of uuid-annotator?
</blockquote></details>

Yes! Thank you for catching that. ... I guess you know where I got the example from now :)
___
*[`cmd/example-eventsocket-client/main.go` line 49 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uGLpA87EyZF89Z-l4:-N3uXggC6kv1xHw7Po7I:b-896fix) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L49)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

Looks good.
</blockquote></details>

Done.
___
*[`cmd/example-eventsocket-client/main.go` line 70 at r1](https://reviewable.io/reviews/m-lab/tcp-info/130#-N3uWj6cBy3LMSG9Epar:-N3uY_g7DpST3q0b8lWc:b-896fix) ([raw file](https://github.com/m-lab/tcp-info/blob/90b730ad7cdf6b760c27f1e13e2c721b6903cc26/cmd/example-eventsocket-client/main.go#L70)):*
<details><summary><i>Previously, SaiedKazemi (Saied Kazemi) wrote…</i></summary><blockquote>

s/even/event/
</blockquote></details>

Done.

**Comment by stephen-soltesz** [comment]
@SaiedKazemi would you "approve in github"? There may be an alternate button in reviewable or directly in github.

**Review by SaiedKazemi — APPROVED** [review]

**Pull request merged**
